### ISSUE TITLE
Exam date tracking

### ISSUE THREAD

**Issue by w-lfchen** [w-lfchen/Alfred-2#3]
Current plan:
Add a command that takes a link to an excel spreadsheet such as [this one](https://www.intern.tu-darmstadt.de/media/dezernat_ii/referat_iif/pruefungen_5/Pruefungen_SoSe_2024_Studierende.xlsx).
Download the sheet and then extract the data and store it in a database which can then be queried through further commands.
TODO:
- [ ] Decide on a database to use (currently heavily leaning towards postgres)
- [ ] Figure out how to download an excel file and extract data from it
- [ ] Come up with a database schema
- [ ] Figure out what data to store
- [ ] Implement everything
